source 'https://rubygems.org'
gem 'sinatra', '~> 2.1'
gem 'mongoid', '~> 7.3'
gem 'jwt',     '~> 2.6'
gem 'bcrypt',  '~> 3.1'
gem 'rack-cors', '~> 1.1'
gem 'pony',    '~> 2.18'    # for email notifications (optional)
